name: Auto Merge PR

on:
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PR Labels and Status
        id: check-conditions
        run: |
          if [[ -z "${{ github.event.check_suite.pull_requests[0].number }}" ]]; then
            echo "This check suite is not associated with a pull request."
            exit 0
          fi

          PR_NUMBER=${{ github.event.check_suite.pull_requests[0].number }}
          
          PR_LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          PR_MERGEABLE=$(gh pr view $PR_NUMBER --json mergeable --jq '.mergeable')
          PR_STATE=$(gh pr view $PR_NUMBER --json isReadyForReview --jq '.isReadyForReview')

          echo "PR Labels: $PR_LABELS"
          echo "PR Mergeable: $PR_MERGEABLE"
          echo "PR Ready for Review: $PR_STATE"

          if [[ "$PR_LABELS" != *"auto-merge"* ]]; then
            echo "This PR does not have the 'auto-merge' label."
            exit 0
          fi

          if [[ "$PR_MERGEABLE" != "true" ]]; then
            echo "This PR is not mergeable yet."
            exit 0
          fi

          echo "::set-output name=can_merge::true"

      - name: Merge the PR
        if: steps.check-conditions.outputs.can_merge == 'true'
        run: |
          gh pr merge ${{ github.event.check_suite.pull_requests[0].number }} --merge --delete-branch --admin
