name: Status Check Example

on:
  pull_request:  # 针对 PR 事件触发
    branches:
      - master     # 限制为对 main 分支的更改

jobs:
  status-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Status Check
        run: |
          echo "Running status checks..."
          # 模拟一个任务，例如运行测试
          echo "Tests passed!"
